# Generated by Django 2.1.7 on 2019-04-11 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasAspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('top', models.FloatField()),
                ('left', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('svg_url', models.CharField(blank=True, max_length=50)),
                ('stroke_width', models.FloatField(blank=True)),
                ('fill', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalAspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_usage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('canvas_aspect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.CanvasAspect')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('canvas_aspect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.CanvasAspect')),
                ('electrical_aspect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planner.ElectricalAspect')),
            ],
        ),
        migrations.CreateModel(
            name='WaterAspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_increase', models.FloatField()),
                ('is_open', models.BooleanField()),
                ('following_items', models.ManyToManyField(blank=True, related_name='previous_items', to='planner.WaterAspect')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='planner.ItemType'),
        ),
    ]
