# Generated by Django 2.1.7 on 2019-03-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasAspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('top', models.FloatField()),
                ('left', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('url', models.CharField(blank=True, max_length=50)),
                ('strokeWidth', models.FloatField(blank=True)),
                ('fill', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('canvasAspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CanvasAspect')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('canvasAspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.CanvasAspect')),
            ],
        ),
    ]
