# Generated by Django 2.2 on 2019-04-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateraspect',
            name='following_items',
            field=models.ManyToManyField(blank=True, related_name='previous_items', to='planner.WaterAspect'),
        ),
    ]
