# Generated by Django 2.1.7 on 2019-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasaspect',
            name='fill',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
