# Generated by Django 2.1.7 on 2019-03-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20190329_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canvasaspect',
            old_name='url',
            new_name='svgUrl',
        ),
    ]
